#!/usr/bin/env node

var spawn = require('child_process').spawn
var concat = require('concat-stream')

install()

function install () {
  console.log('installing glsl stuff')
  spawn('glslify', [process.argv.slice(2)[0]]).stderr.pipe(concat(done, { encoding: 'object' }))
}

function done (buffer) {
  var missing = buffer.toString().match(/Cannot find module '([^']*)'/)
  if (missing) {
    missing = missing[1]
    console.log('installing', missing)
    var ps = spawn('npm', ['i', missing, process.env.NPM_ARGS])
    ps.on('exit', install)
  }
}
